export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-no-repeat min-h-screen">
        <aside>sidebar</aside>
        {children}
        <footer>Rasonix copyright</footer>
      </body>
    </html>
  );
}
